#!/bin/sh
#Script to update SymLinks to Jetbrains tools after update.
patternNormal="(([0-9]){3}\.([0-9]){4}\.([0-9]){2}$)"
patternAndroid="(([0-9]){3}\.([0-9]){7}$)"
patternWebStorm="(([0-9]){3}\.([0-9]){4}\.([0-9])$)"

alias echo="echo -e"
#colors
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "Please choose program to update SymLink of"
echo "------------------------------------------"

changeLink () {

    if [ "$Input" = "pycharm" ]; then 
        ide="PyCharm-P"
    elif [ "$Input" = "idea" ]; then 
        ide="IDEA-U"
    elif [ "$Input" = "studio" ]; then
        ide="AndroidStudio"
    elif [ "$Input" = "clion" ]; then
        ide="CLion"
    elif [ "$Input" = "webstorm" ]; then
        ide="WebStorm"
    else 
        echo "${RED} No supported program${NC}"
        return
    fi

    {
        rm /home/jast/.local/bin/$Input &>/dev/null && echo "${BLUE}Deleted old SymLink for $Input${NC}"
    } || {
        echo "${RED}No old SymLink for $Input found${NC}"
    }


    for dir in /home/jast/.local/share/JetBrains/Toolbox/apps/$ide/ch-0/* ; do
        name=$(basename $dir)
        if [ "$ide" = "AndroidStudio" ];then
            [[ $name =~ $patternAndroid ]]
        elif [ "$ide" = "WebStorm" ]; then
            [[ $name =~ $patternNormal ]]
        else
            [[ $name =~ $patternNormal ]]
        fi
        if [ ! ${#BASH_REMATCH[1]} -eq 0 ]; then 
            test="${BASH_REMATCH[1]}"
        fi
    done

    {
        ln -s /home/jast/.local/share/JetBrains/Toolbox/apps/$ide/ch-0/$test/bin/${Input}.sh ~/.local/bin/$Input &>/dev/null && echo "${BLUE}Created new SymLink for $ide with name $Input${NC}"
    } || {
        echo "something went wrong"
    }
}

PS3="Enter number: "
select option in pycharm idea studio clion webstorm Exit
do
    case $option in
        Exit)
            echo "${RED}----------------------------${NC}"
            echo "${RED}EXIT${NC}"
            exit
            ;;
        *)
            Input=$option
            echo "----------------------------"
            echo "Changing Symlink for $option"
            echo "----------------------------"
            changeLink $Input
    esac
done
